=== 0semter0/cosmos-chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "object",
            "properties": {
                "genesis_url": {
                    "type": "string"
                }
            }
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "secp256k1",
                    "ethsecp256k1",
                    "ed25519",
                    "sr25519"
                ],
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "fees": {
            "type": "object",
            "properties": {
                "fee_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/fee_token"
                    }
                }
            }
        },
        "staking": {
            "type": "object",
            "properties": {
                "staking_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/staking_token"
                    }
                },
                "staking_systems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/staking_system"
                    }
                }
            }
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "recommended_version",
                "compatible_versions"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "recommended_version": {
                    "type": "string"
                },
                "compatible_versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            }
        },
        "explorers": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/explorer"
            }
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "explorer": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "tx_page": {
                    "type": "string"
                },
                "account_page": {
                    "type": "string"
                }
            }
        },
        "fee_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                },
                "fixed_min_gas_price": {
                    "type": "number"
                }
            }
        },
        "staking_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                }
            }
        },
        "staking_system": {
            "oneOf": [
                {
                    "const": "superfluid",
                    "description": "Enables liquidity providers on this network to utilize AMM-pooled staking tokens for governance and delegation. As seen on Osmosis."
                },
                {
                    "const": "interfluid",
                    "description": "Enables liquidity providers on a foreign network to utilize AMM-pooled staking tokens for governance and delegation. Soon provided by Osmosis."
                },
                {
                    "const": "interchain",
                    "description": "Enables this network to be secured by the validator set of another network. As to be seen on Neutron."
                },
                {
                    "const": "whitelisted-liquid",
                    "description": "Utilizes a protocol-permissioned whitelist to issue liquid staking derivatives. As seen on Crescent Network."
                },
                {
                    "const": "iqlusion-liquid",
                    "description": "Enables this network to permissionlessly issue validator-specific liquid staking derivatives without unbonding. Coming soon to Cosmos Hub."
                }
            ]
        },
        "logo_URIs": {
            "type": "object",
            "properties": {
                "png": {
                    "type": "string",
                    "format": "uri-reference"
                },
                "svg": {
                    "type": "string",
                    "format": "uri-reference"
                }
            }
        }
    }
}

=== 0semter0/cosmos-chain-registry/carbon/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "carbon",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Carbon",
  "chain_id": "carbon-1",
  "bech32_prefix": "swth",
  "daemon_name": "carbond",
  "node_home": "$HOME/.carbond",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "swth",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "usc",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "bnb.1.6.773edb",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "bneo.1.14.e2e5f6",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "busd.1.6.754a80",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "eth.1.2.942d87",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "ibc/75249A18DEFBEFE55F83B1C70CAD234DF164F174C6BC51682EE92C2C81C18C93",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "ibc/A4DB47A9D3CF9A068D454513891B526702455D3EF08FB9EB558C561F9DC2B701",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "ibc/B7864B03E1B9FD4F049243E92ABD691586F682137037A9F3FCA5222815620B3C",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "usdc.1.2.343151",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      },
      {
        "denom": "usdc.1.6.53ff75",
        "fixed_min_gas_price": 0,
        "low_gas_price": 1,
        "average_gas_price": 1.5,
        "high_gas_price": 2
      }
    ]
  },
  "staking": {
    "staking_tokens": [
      {
        "denom": "swth"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/Switcheo/carbon-bootstrap",
    "recommended_version": "v2.15.6",
    "compatible_versions": [
      "v2.15.6"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/Switcheo/carbon-bootstrap/releases/download/v2.15.6/carbond2.15.6-mainnet.linux-amd64.tar.gz",
      "linux/arm64": "https://github.com/Switcheo/carbon-bootstrap/releases/download/v2.15.6/carbond2.15.6-mainnet.linux-arm64.tar.gz"
    },
    "genesis": {
      "genesis_url": "https://github.com/Switcheo/carbon-bootstrap/raw/master/carbon-1/genesis.json"
    }
  },
  "peers": {
    "seeds": [
      {
        "id": "d93ed6a1f43dd0904dc5e2ab8680d4049b057b17",
        "address": "13.215.17.91:26656",
        "provider": "switcheo-labs"
      },
      {
        "id": "70581c625fc1933bc273ca7a8d5e9ded3d1bcc97",
        "address": "13.213.113.113:26656",
        "provider": "switcheo-labs"
      },
      {
        "id": "e3f02a9f3ca22724b3a67bba9183113645c9c7d9",
        "address": "54.179.11.177:26656",
        "provider": "switcheo-labs"
      }
    ],
    "persistent_peers": [
      {
        "id": "b638cc8fc5b3d7867281081efce15e5a989339ac",
        "address": "188.166.191.195:26656",
        "provider": "intsol"
      },
      {
        "id": "aa238fc5a6b3f2a305a4ffb56a636ce14adce371",
        "address": "alice.peers.carbon.bh.rocks:26656",
        "provider": "BlockHunters"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://tm-api.carbon.network",
        "provider": "switcheo-labs"
      },
      {
        "address": "https://rpc.carbon.bh.rocks",
        "provider": "BlockHunters"
      }
    ],
    "rest": [
      {
        "address": "https://api.carbon.network",
        "provider": "switcheo-labs"
      },
      {
        "address": "https://rest.carbon.bh.rocks",
        "provider": "BlockHunters"
      }
    ]
  },
  "explorers": [
    {
      "kind": "carbonscan",
      "url": "https://scan.carbon.network",
      "tx_page": "https://scan.carbon.network/transaction/${txHash}?net=main"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/planq/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "planq",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Planq",
  "chain_id": "planq_7070-2",
  "bech32_prefix": "plq",
  "node_home": "$HOME/.planqd",
  "genesis": {
    "genesis_url": "https://archive.evmos.org/mainnet/genesis.json"
  },
  "daemon_name": "planqd",
  "slip44": 60,
  "fees": {
    "fee_tokens": [
      {
        "denom": "aplanq",
        "low_gas_price": 10000000000,
        "average_gas_price": 25000000000,
        "high_gas_price": 40000000000
      }
    ]
  },
  "staking": {
    "staking_tokens": [
        {
            "denom": "aplanq"
        }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/planq-network/planq",
    "recommended_version": "v1.0.0",
    "compatible_versions": ["v1.0.0"]
  },
  "peers": {
    "seeds": [
      {
        "id": "dd2f0ceaa0b21491ecae17413b242d69916550ae",
        "address": "135.125.247.70:26656",
        "provider": "Planq Foundation EU"
      },
      {
        "id": "0525de7e7640008d2a2e01d1a7f6456f28f3324c",
        "address": "51.79.142.6:26656",
        "provider": "Planq Foundation SG"
      },
      {
        "id": "21432722b67540f6b366806dff295849738d7865",
        "address": "139.99.223.241:26656",
        "provider": "Planq Foundation AU"
      }
    ],
    "persistent_peers": [
      {
        "id": "dd2f0ceaa0b21491ecae17413b242d69916550ae",
        "address": "135.125.247.70:26656",
        "provider": "Planq Foundation EU"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.planq.network",
        "provider": "planq.network"
      }
    ],
    "rest": [
      {
        "address": "https://rest.planq.network",
        "provider": "planq.network"
      }
    ],
    "grpc": [
      {
        "address": "https://grpc.planq.network",
        "provider": "planq.network"
      }
    ],
    "evm-http-jsonrpc": [
      {
        "address": "https://evm-rpc.planq.network",
        "provider": "planq.network"
      }
    ]
  },
  "explorers": [
    {
      "kind": "bigdipper",
      "url": "https://explorer.planq.network",
      "tx_page": "https://explorer.planq.network/transactions/${txHash}"
    },
    {
      "kind": "blockscout",
      "url": "https://evm.planq.network",
      "tx_page": "https://evm.planq.network/tx/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/clannetwork/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "clannetwork",
  "status": "live",
  "network_type": "testnet",
  "pretty_name": "Clan Network",
  "chain_id": "playstation-2",
  "bech32_prefix": "clan",
  "daemon_name": "cland",
  "node_home": "$HOME/.clan",
  "genesis": {
    "genesis_url": "https://raw.githubusercontent.com/ClanNetwork/testnets/main/playstation-2/genesis.json"
  },
  "key_algos": ["secp256k1"],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "uclan",
        "fixed_min_gas_price": 0.00
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/ClanNetwork/clan-network",
    "recommended_version": "v1.2.0",
    "binaries": {
      "linux/amd64": "https://github.com/ClanNetwork/clan-network/releases/download/v1.0.4-alpha/clan-network_v1.0.4-alpha_linux_amd64.tar.gz"
    },
    "compatible_versions": ["v1.0.4-alpha"]
  },
  "peers": {
    "persistent_peers": [
      {
        "id": "ccf7ec7554e3e8ca8f1583d9c943e19a8f32e428",
        "address": "162.251.235.239:26656",
        "provider": "secretnodes.com"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "",
        "provider": ""
      },
      {
        "address": "",
        "provider": ""
      },
      {
        "address": "",
        "provider": ""
      }
    ],
    "rest": [
      {
        "address": "",
        "provider": ""
      },
      {
        "address": "",
        "provider": ""
      }
    ],
    "grpc-web": [
      {
        "address": "",
        "provider": ""
      }
    ]
  },
  "explorers": [
    {
      "kind": "secret nodes",
      "url": "https://secretnodes.com/clan/chains/playstation-2",
      "tx_page": "https://secretnodes.com/clan/chains/playstation-2/transactions/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/lumenx/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "lumenx",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "LumenX",
  "chain_id": "LumenX",
  "bech32_prefix": "lumen",
  "daemon_name": "lumenxd",
  "node_home": "$HOME/.lumenx",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "ulumen",
        "fixed_min_gas_price": 0.0025
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/metaprotocol-ai/lumenx",
    "recommended_version": "v0.1.0",
    "compatible_versions": [
      "v0.1.0"
    ],
    "genesis": {
      "genesis_url": "https://raw.githubusercontent.com/metaprotocol-ai/lumenx/master/config/genesis.json"
    }
  },
  "peers": {
    "seeds": [],
    "persistent_peers": []
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.lumenx.chaintools.tech/",
        "provider": "ChainTools"
      },
      {
        "address": "https://rpc-lumenx.cryptonet.pl/",
        "provider": "CryptoNet"
      }
    ],
    "rest": [
      {
        "address": "https://api.lumenx.chaintools.tech/",
        "provider": "ChainTools"
      },
      {
        "address": "https://api-lumenx.cryptonet.pl/",
        "provider": "CryptoNet"
      }
    ]
  },
  "explorers": [
    {
      "kind": "ping.pub",
      "url": "https://explorer.chaintools.tech/lumenx",
      "tx_page": "https://explorer.chaintools.tech/lumenx/tx/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/testnets/deardogstestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chain_name": "deardogstestnet",
  "chain_id": "vota-flatsat",
  "pretty_name": "Dear Dogs Testnet",
  "status": "live",
  "network_type": "testnet",
  "bech32_prefix": "dora",
  "daemon_name": "dorad",
  "node_home": "$HOME/.dora",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "peaka",
        "fixed_min_gas_price": 100000000000
      }
    ]
  },
  "staking": {
    "staking_tokens": [
      {
        "denom": "peaka"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/dorafactory/doravota",
    "recommended_version": "v11.0.0",
    "compatible_versions": [
      "v11.0.0"
    ],
    "binaries": {
    },
    "genesis": {
      "genesis_url": "https://github.com/DoraFactory/doravota/blob/main/config/testnet/genesis.json"
    },
    "versions": [
      {
        "name": "v9.0.1",
        "recommended_version": "v9.0.1",
        "compatible_versions": [
          "v9.0.1"
        ],
        "binaries": {
        }
      },
      {
        "name": "v10.0.1",
        "recommended_version": "v10.0.1",
        "compatible_versions": [
          "v10.0.1"
        ],
        "binaries": {
        }
      },
      {
        "name": "v11",
        "recommended_version": "v11.0.0",
        "compatible_versions": [
          "v11.0.0"
        ],
        "binaries": {
        }
      }
    ]
  },
  "peers": {
    "seeds": [
    ],
    "persistent_peers": []
  },
  "apis": {
    "rpc": [
      {
        "address": "https://doge-testnet-rpc.dorafactory.org",
        "provider": "dorafactory"
      }
    ],
    "rest": [
      {
        "address": "https://doge-testnet-rest.dorafactory.org",
        "provider": "dorafactory"
      }
    ],
    "grpc": [
      {
        "address": "doge-testnet-grpc.dorafactory.org:443",
        "provider": "dorafactory"
      }
    ]
  },
  "explorers": [
    {
      "kind": "Dear Dogs Ping Pub",
      "url": "https://doge-testnet-explorer.dorafactory.org",
      "tx_page": "https://doge-testnet-explorer.dorafactory.org/deardogstestnet/tx/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/thornode/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "thornode",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "THORChain",
    "chain_id": "thor-1",
    "bech32_prefix": "rune",
    "daemon_name": "thord",
    "node_home": "$HOME/.thornode",
    "slip44": 931,
    "genesis": {
        "genesis_url": "https://rpc.thorchain.info/genesis"
    },
    "codebase": {
        "git_repo": "https://github.com/thorchain/thornode",
        "recommended_version": "master",
        "compatible_versions": [
            "master"
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://btc.thorchain.info",
                "provider": "btc"
            },
            {
                "address": "https://bch.thorchain.info",
                "provider": "bch"
            },
            {
                "address": "https://ltc.thorchain.info",
                "provider": "ltc"
            },
            {
                "address": "https://bnb.thorchain.info",
                "provider": "bnb"
            },
            {
                "address": "https://eth.thorchain.info",
                "provider": "eth"
            }
        ],
        "rest": [
            {
                "address": "https://thornode.thorchain.info",
                "provider": "thornode"
            }
        ]
    },
    "explorers": [
        {
            "kind": "THORChain explorer",
            "url": "https://thorchain.net",
            "tx_page": "https://thorchain.net/#/txs/${txHash}"
        },
        {
            "kind": "viewblock",
            "url": "https://viewblock.io/thorchain",
            "tx_page": "https://viewblock.io/thorchain/tx/${txHash}"
        }
    ]
}

=== 0semter0/cosmos-chain-registry/kujira/chain.json
{
    "$schema": "../../chain.schema.json",
    "chain_name": "kujira",
    "chain_id": "kaiyo-1",
    "pretty_name": "Kujira",
    "status": "live",
    "network_type": "mainnet",
    "bech32_prefix": "kujira",
    "genesis": {
        "genesis_url": "https://github.com/Team-Kujira/networks/raw/master/mainnet/kaiyo-1.json"
    },
    "daemon_name": "kujirad",
    "node_home": "$HOME/.kujira",
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "ukuji",
                "fixed_min_gas_price": 0
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/Team-Kujira/core",
        "recommended_version": "v0.4.0",
        "compatible_versions": [
            "v0.4.0"
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://kujira-rpc.polkachu.com",
                "provider": "polkachu"
            }
        ],
        "rest": [
            {
                "address": "https://kujira-api.polkachu.com/",
                "provider": "polkachu"
            }
        ]
    },
    "explorers": [
        {
            "kind": "explorers.guru",
            "url": "https://kujira.explorers.guru",
            "tx_page": "https://kujira.explorers.guru/transaction/${txHash}"
        }
    ]
}

=== 0semter0/cosmos-chain-registry/terpnetwork/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "terpnettestnet",
    "status": "upcoming",
    "network_type": "mainnet",
    "pretty_name": "Terp-Network",
    "chain_id": "morocco-1",
    "bech32_prefix": "terp",
    "daemon_name": "terp",
    "node_home": "$HOME/.terp",
    "codebase": {
      "git_repo": "https://github.com/terpnetwork/terp-core.git",
      "recommended_version": "v1.0.0",
      "consensus": {
        "type": "cometbft",
        "version": "0.37.0"
      },
      "compatible_versions": [
        "v1.0.0"
      ],
      
      "genesis": {
        "genesis_url": ""
      },
      "binaries": {
        "linux/amd64": "https://github.com/terpnetwork/terp-core/archive/refs/tags/v1.0.0.tar.gz"
      },
      "versions": [
        {
          "name": "v1.0.0",
          "recommended_version": "v1.0.0",
          "compatible_versions": [
            "v1.0.0"
          ],
          "consensus": {
            "type": "cometbft",
            "version": "0.37.0"
          },
          "binaries": {
            "linux/amd64": "https://github.com/terpnetwork/terp-core/archive/refs/tags/v1.0.0.tar.gz"
        }
        }
      ]
    },
    "peers": {
      "seeds": [],
      "persistent_peers": [
        {
          "id": "",
          "address": ""
        }
      ]
    },
    "apis": {
      "rpc": [
        {
          "address": "",
          "provider": ""
        }
      ],
      "rest": [
        {
            "address": "",
            "provider": ""
        }
      ],
      "grpc": [
        {
            "address": "",
            "provider": ""
        }
      ]
    },
    "explorers": [
      {
        "kind": "",
        "url": "",
        "tx_page": ""
      }
    ]
  }
