=== 0semter0/cosmos-chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "object",
            "properties": {
                "genesis_url": {
                    "type": "string"
                }
            }
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "secp256k1",
                    "ethsecp256k1",
                    "ed25519",
                    "sr25519"
                ],
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "fees": {
            "type": "object",
            "properties": {
                "fee_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/fee_token"
                    }
                }
            }
        },
        "staking": {
            "type": "object",
            "properties": {
                "staking_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/staking_token"
                    }
                },
                "staking_systems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/staking_system"
                    }
                }
            }
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "recommended_version",
                "compatible_versions"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "recommended_version": {
                    "type": "string"
                },
                "compatible_versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            }
        },
        "explorers": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/explorer"
            }
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "explorer": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "tx_page": {
                    "type": "string"
                },
                "account_page": {
                    "type": "string"
                }
            }
        },
        "fee_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                },
                "fixed_min_gas_price": {
                    "type": "number"
                }
            }
        },
        "staking_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                }
            }
        },
        "staking_system": {
            "oneOf": [
                {
                    "const": "superfluid",
                    "description": "Enables liquidity providers on this network to utilize AMM-pooled staking tokens for governance and delegation. As seen on Osmosis."
                },
                {
                    "const": "interfluid",
                    "description": "Enables liquidity providers on a foreign network to utilize AMM-pooled staking tokens for governance and delegation. Soon provided by Osmosis."
                },
                {
                    "const": "interchain",
                    "description": "Enables this network to be secured by the validator set of another network. As to be seen on Neutron."
                },
                {
                    "const": "whitelisted-liquid",
                    "description": "Utilizes a protocol-permissioned whitelist to issue liquid staking derivatives. As seen on Crescent Network."
                },
                {
                    "const": "iqlusion-liquid",
                    "description": "Enables this network to permissionlessly issue validator-specific liquid staking derivatives without unbonding. Coming soon to Cosmos Hub."
                }
            ]
        },
        "logo_URIs": {
            "type": "object",
            "properties": {
                "png": {
                    "type": "string",
                    "format": "uri-reference"
                },
                "svg": {
                    "type": "string",
                    "format": "uri-reference"
                }
            }
        }
    }
}

=== 0semter0/cosmos-chain-registry/terpnet/chain.json
{
  "chain_name": "TerpNet",
  "status": "live",
  "network_type": "testnet",
  "pretty_name": "Terp-Net",
  "chain_id": "athena-1",
  "bech32_prefix": "terp",
  "daemon_name": "terp",
  "node_home": "$HOME/.terp",
  "genesis": {
    "genesis_url": 
"https://raw.githubusercontent.com/terpnetwork/test-net/master/athena-1/genesis.json"
  },
  "codebase": {
    "git_repo": "github.com/terpnetwork/terp-core",
    "recommended_version": "v0.1.0",
    "compatible_versions": [
      "v0.1.0"
    ],
    "binaries": {
      "linux/amd64": 
"https://github.com/terpnetwork/terp-core/archive/refs/tags/v0.1.0.tar.gz"
    }
  },
  "peers": {
    "seeds": [
      
      {
        "id": "5a6f4f80c7a29055028fc503216a1539594ad33f",
        "address": "89.111.15.146:11513"
      }
    ],
    "persistent_peers": [
      
      {
        "id": "7e5c0b9384a1b9636f1c670d5dc91ba4721ab1ca",
        "address": "23.88.53.28:36656"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "http://23.88.53.28:36657"
      },
      {
        "address": "https://rpc-terp.zenchainlabs.io/"
      },
      {
        "address": "https://terp-rpc.skynetvalidators.com/"
      },
      {
        "address": "https://terp-rpc.skynetvalidators.com/"
      }
      
    ],
    "rest": [
      {
        "address": "https://api-terp.zenchainlabs.io/",
        "provider": "Zenchain Labs"
      },
      {
        "address": "https://terp-api.skynetvalidators.com",
        "provider": "skynet validators"
      }
      
    ],
    "grpc": [
      {
        "address": "23.88.53.28:36090",
        "provider": "HighStakes"
      }
    ]
  }
}

=== 0semter0/cosmos-chain-registry/teritori/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "teritori",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Teritori",
  "chain_id": "teritori-1",
  "daemon_name": "teritorid",
  "node_home": "$HOME/.teritorid",
  "bech32_prefix": "teri",
  "genesis": {
    "genesis_url": "https://github.com/TERITORI/teritori-mainnet-genesis/raw/main/genesis.json"
  },
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "utori",
        "low_gas_price": 0.5,
        "average_gas_price": 0.75,
        "high_gas_price": 1
      }
    ]
  },
  "staking": {
    "staking_tokens": [
      {
        "denom": "utori"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/TERITORI/teritori-chain",
    "recommended_version": "v1.0.0",
    "compatible_versions": [
      "v1.0.0"
    ]
  },
  "peers": {
    "seeds": [
      {
        "id": "20e1000e88125698264454a884812746c2eb4807",
        "address": "seeds.lavenderfive.com:15956",
        "provider": "Lavender.Five Nodes 🐝"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://teritori-rpc.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes 🐝"
      }
    ],
    "rest": [
      {
        "address": "https://teritori-api.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes 🐝"
      }
    ],
    "grpc": [
      {
        "address": "https://teritori-grpc.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes 🐝"
      }
    ]
  },
  "explorers": [

  ]
}

=== 0semter0/cosmos-chain-registry/celestia/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "celestia",
  "chain_id": "celestia",
  "pretty_name": "Celestia",
  "status": "live",
  "network_type": "mainnet",
  "bech32_prefix": "celestia",
  "daemon_name": "celestia-appd",
  "node_home": "$HOME/.celestia-app",
  "key_algos": ["secp256k1"],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "utia",
        "fixed_min_gas_price": 0,
        "low_gas_price": 0.4,
        "average_gas_price": 0.1,
        "high_gas_price": 0.2
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/celestiaorg/celestia-app",
    "recommended_version": "v1.3.0",
    "compatible_versions": ["v1.3.0"],
    "genesis": {
      "genesis_url": "https://raw.githubusercontent.com/celestiaorg/networks/master/celestia/genesis.json"
    },
    "versions": [
      {
        "name": "v1.3.0",
        "recommended_version": "v1.3.0",
        "compatible_versions": ["v1.3.0"]
      }
    ]
  },
  "peers": {
    "seeds": [
      {
        "id": "f97a75fb69d3a5fe893dca7c8d238ccc0bd66a8f",
        "address": "celestia-blockspacerace.seed.brocha.in:30583",
        "provider": "Celestia Labs"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.lunaroasis.net",
        "provider": "Celestia Labs"
      }
    ],
    "rest": [
      {
        "address": "https://api.lunaroasis.net",
        "provider": "Celestia Labs"
      }
    ]
  },
  "explorers": [
    {
      "kind": "Mintscan",
      "url": "https://mintscan.io/celestia",
      "tx_page": "https://mintscan.io/celestia/txs/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/chronicnetwork/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "chronicnetwork",
  "status": "killed",
  "network_type": "mainnet",
  "pretty_name": "Chronic Chain",
  "chain_id": "morocco-1",
  "bech32_prefix": "chronic",
  "daemon_name": "chtd",
  "node_home": "$HOME/.cht",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "ucgas",
        "fixed_min_gas_price": 0.001
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/ChronicNetwork/cht",
    "recommended_version": "v1.1.0",
    "compatible_versions": [
      "v1.1.0"
    ],
    "binaries": {},
    "genesis": {},
    "versions": [
      {
        "name": "v1.1.0",
        "recommended_version": "v1.1.0",
        "compatible_versions": [],
        "binaries": {}
      }
    ]
  },
  "peers": {
    "seeds": [],
    "persistent_peers": []
  },
  "apis": {
    "rpc": [],
    "rest": [],
    "grpc": []
  },
  "explorers": []
}

=== 0semter0/cosmos-chain-registry/testnets/synternettestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chain_name": "synternettestnet",
  "chain_id": "amber-2",
  "pretty_name": "Amber Public Testnet",
  "status": "live",
  "network_type": "testnet",
  "bech32_prefix": "amber",
  "daemon_name": "amberd",
  "node_home": "$HOME/.amber",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "uamber",
        "fixed_min_gas_price": 0.005,
        "low_gas_price": 0.01,
        "average_gas_price": 0.025,
        "high_gas_price": 0.03
      }
    ]
  },
  "staking": {
    "staking_tokens": [
      {
        "denom": "uamber"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/Synternet/synternet-chain-releases",
    "recommended_version": "v0.8.0",
    "compatible_versions": [
      "v0.8.0"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.8.0/amberd-linux-amd64-v0.8.0-testnet"
    },
    "genesis": {
      "genesis_url": "https://github.com/Synternet/synternet-chain-releases/blob/main/networks/testnet/genesis.json"
    },
    "versions": [
      {
        "name": "v0.1",
        "recommended_version": "v0.1.0",
        "compatible_versions": [
          "v0.1.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.0.1/amberd-linux-amd64-v0.1.0-testnet"
        }
      },
      {
        "name": "v0.2",
        "recommended_version": "v0.2.4",
        "compatible_versions": [
          "v0.2.4"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.2.4/amberd-linux-amd64-v0.2.4-testnet"
        }
      },
      {
        "name": "v0.5",
        "recommended_version": "v0.5.4",
        "compatible_versions": [
          "v0.5.4"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.5.4/amberd-linux-amd64-v0.5.4-testnet"
        }
      },
      {
        "name": "v0.6",
        "recommended_version": "v0.6.0",
        "compatible_versions": [
          "v0.6.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.6.0/amberd-linux-amd64-v0.6.0-testnet"
        }
      },
      {
        "name": "v0.7",
        "recommended_version": "v0.7.0",
        "compatible_versions": [
          "v0.7.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.7.0/amberd-linux-amd64-v0.7.0-testnet"
        }
      },
      {
        "name": "v0.8",
        "recommended_version": "v0.8.0",
        "compatible_versions": [
          "v0.8.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/Synternet/synternet-chain-releases/releases/download/v0.8.0/amberd-linux-amd64-v0.8.0-testnet"
        }
      }
    ]
  },
  "peers": {
    "seeds": [
      {
        "id": "639d50339d7045436c756a042906b9a69970913f",
        "address": "seed-01.theta-testnet.polypore.xyz:26656",
        "provider": "Hypha"
      },
      {
        "id": "3e506472683ceb7ed75c1578d092c79785c27857",
        "address": "seed-02.theta-testnet.polypore.xyz:26656",
        "provider": "Hypha"
      }
    ],
    "persistent_peers": []
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.sentry-01.theta-testnet.polypore.xyz",
        "provider": "Hypha"
      },
      {
        "address": "https://rpc.sentry-02.theta-testnet.polypore.xyz",
        "provider": "Hypha"
      }
    ],
    "rest": [
      {
        "address": "https://rest.sentry-01.theta-testnet.polypore.xyz",
        "provider": "Hypha"
      },
      {
        "address": "https://rest.sentry-02.theta-testnet.polypore.xyz",
        "provider": "Hypha"
      }
    ],
    "grpc": [
      {
        "address": "https://grpc.sentry-01.theta-testnet.polypore.xyz",
        "provider": "Hypha"
      },
      {
        "address": "https://grpc.sentry-02.theta-testnet.polypore.xyz",
        "provider": "Hypha"
      }
    ]
  },
  "explorers": [
    {
      "kind": "Mintscan",
      "url": "https://mintscan.io/cosmoshub-testnet",
      "tx_page": "https://mintscan.io/cosmoshub-testnet/txs/${txHash}"
    },
    {
      "kind": "Big Dipper",
      "url": "https://explorer.theta-testnet.polypore.xyz/",
      "tx_page": "https://explorer.theta-testnet.polypore.xyz/transactions/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/kyve/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "kyve",
  "chain_id": "kyve-1",
  "pretty_name": "KYVE",
  "status": "live",
  "network_type": "mainnet",
  "bech32_prefix": "kyve",
  "daemon_name": "kyved",
  "node_home": "$HOME/.kyve",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "ukyve",
        "fixed_min_gas_price": 0
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/KYVENetwork/chain",
    "recommended_version": "v1.0.0",
    "compatible_versions": [
      "v1.0.0"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/KYVENetwork/chain/releases/download/v1.0.0/kyved_linux_amd64.tar.gz",
      "linux/arm64": "https://github.com/KYVENetwork/chain/releases/download/v1.0.0/kyved_linux_arm64.tar.gz",
      "darwin/amd64": "https://github.com/KYVENetwork/chain/releases/download/v1.0.0/kyved_darwin_amd64.tar.gz",
      "darwin/arm64": "https://github.com/KYVENetwork/chain/releases/download/v1.0.0/kyved_darwin_arm64.tar.gz"
    },
    "genesis": {
      "genesis_url": "https://raw.githubusercontent.com/KYVENetwork/networks/main/kyve-1/genesis.json"
    }
  },
  "peers": {
    "persistent_peers": [
      {
        "id": "fae8cd5f04406e64484a7a8b6719eacbb861c094",
        "address": "44.241.103.199:26656"
      },
      {
        "id": "146d27829fd240e0e4672700514e9835cb6fdd98",
        "address": "34.212.201.1:26656"
      },
      {
        "id": "25da6253fc8740893277630461eb34c2e4daf545",
        "address": "3.76.244.30:26656"
      },
      {
        "id": "b950b6b08f7a6d5c3e068fcd263802b336ffe047",
        "address": "18.198.182.214:26656"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc-kyve.ecostake.com",
        "provider": "ecostake"
      }
    ],
    "rest": [
      {
        "address": "https://rest-kyve.ecostake.com",
        "provider": "ecostake"
      }
    ]
  },
  "explorers": [
    {
      "kind": "mintscan",
      "url": "https://www.mintscan.io/kyve",
      "tx_page": "https://www.mintscan.io/kyve/txs/${txHash}",
      "account_page": "https://www.mintscan.io/kyve/account/${accountAddress}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/testnets/doravotatestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chain_name": "doravotatestnet",
  "chain_id": "doravota-devnet",
  "pretty_name": "Dora Vota Testnet",
  "status": "live",
  "network_type": "testnet",
  "bech32_prefix": "dora",
  "daemon_name": "dorad",
  "node_home": "$HOME/.dora",
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "uDORA",
        "fixed_min_gas_price": 0.0025
      }
    ]
  },
  "staking": {
    "staking_tokens": [
      {
        "denom": "uDORA"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/dorafactory/doravota",
    "recommended_version": "v11.0.0",
    "compatible_versions": [
      "v11.0.0"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-linux-amd64",
      "linux/arm64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-linux-arm64",
      "darwin/amd64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-darwin-amd64",
      "darwin/arm64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-darwin-arm64",
      "windows/amd64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-windows-amd64.exe",
      "windows/arm64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-windows-arm64.exe"
    },
    "genesis": {
      "genesis_url": "https://github.com/cosmos/testnets/raw/master/public/genesis.json.gz"
    },
    "versions": [
      {
        "name": "v9.0.1",
        "recommended_version": "v9.0.1",
        "compatible_versions": [
          "v9.0.1"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/cosmos/gaia/releases/download/v9.0.1/gaiad-v9.0.1-linux-amd64",
          "linux/arm64": "https://github.com/cosmos/gaia/releases/download/v9.0.1/gaiad-v9.0.1-linux-arm64",
          "darwin/amd64": "https://github.com/cosmos/gaia/releases/download/v9.0.1/gaiad-v9.0.1-darwin-amd64",
          "darwin/arm64": "https://github.com/cosmos/gaia/releases/download/v9.0.1/gaiad-v9.0.1-darwin-arm64",
          "windows/amd64": "https://github.com/cosmos/gaia/releases/download/v9.0.1/gaiad-v9.0.1-windows-amd64.exe"
        }
      },
      {
        "name": "v10.0.1",
        "recommended_version": "v10.0.1",
        "compatible_versions": [
          "v10.0.1"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/cosmos/gaia/releases/download/v10.0.1/gaiad-v10.0.1-linux-amd64",
          "linux/arm64": "https://github.com/cosmos/gaia/releases/download/v10.0.1/gaiad-v10.0.1-linux-arm64",
          "darwin/amd64": "https://github.com/cosmos/gaia/releases/download/v10.0.1/gaiad-v10.0.1-darwin-amd64",
          "darwin/arm64": "https://github.com/cosmos/gaia/releases/download/v10.0.1/gaiad-v10.0.1-darwin-arm64",
          "windows/amd64": "https://github.com/cosmos/gaia/releases/download/v10.0.1/gaiad-v10.0.1-windows-amd64.exe"
        }
      },
      {
        "name": "v11",
        "recommended_version": "v11.0.0",
        "compatible_versions": [
          "v11.0.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-linux-amd64",
          "linux/arm64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-linux-arm64",
          "darwin/amd64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-darwin-amd64",
          "darwin/arm64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-darwin-arm64",
          "windows/amd64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-windows-amd64.exe",
          "windows/arm64": "https://github.com/cosmos/gaia/releases/download/v11.0.0/gaiad-v11.0.0-windows-arm64.exe"
        }
      }
    ]
  },
  "peers": {
    "seeds": [
    ],
    "persistent_peers": []
  },
  "apis": {
    "rpc": [
      {
        "address": "https://vota-rpc.dorafactory.org/",
        "provider": "dorafactory"
      }
    ],
    "rest": [
      {
        "address": "https://vota-rest.dorafactory.org",
        "provider": "dorafactory"
      }
    ],
    "grpc": [
    ]
  },
  "explorers": [
    {
      "kind": "Dora Vota Ping Pub",
      "url": "https://maci-explorer-test.dorafactory.org",
      "tx_page": "https://maci-explorer-test.dorafactory.org/dora/tx/${txHash}"
    }
  ]
}
