=== 0semter0/cosmos-chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "object",
            "properties": {
                "genesis_url": {
                    "type": "string"
                }
            }
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "secp256k1",
                    "ethsecp256k1",
                    "ed25519",
                    "sr25519"
                ],
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "fees": {
            "type": "object",
            "properties": {
                "fee_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/fee_token"
                    }
                }
            }
        },
        "staking": {
            "type": "object",
            "properties": {
                "staking_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/staking_token"
                    }
                },
                "staking_systems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/staking_system"
                    }
                }
            }
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "recommended_version",
                "compatible_versions"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "recommended_version": {
                    "type": "string"
                },
                "compatible_versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            }
        },
        "explorers": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/explorer"
            }
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "explorer": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "tx_page": {
                    "type": "string"
                },
                "account_page": {
                    "type": "string"
                }
            }
        },
        "fee_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                },
                "fixed_min_gas_price": {
                    "type": "number"
                }
            }
        },
        "staking_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                }
            }
        },
        "staking_system": {
            "oneOf": [
                {
                    "const": "superfluid",
                    "description": "Enables liquidity providers on this network to utilize AMM-pooled staking tokens for governance and delegation. As seen on Osmosis."
                },
                {
                    "const": "interfluid",
                    "description": "Enables liquidity providers on a foreign network to utilize AMM-pooled staking tokens for governance and delegation. Soon provided by Osmosis."
                },
                {
                    "const": "interchain",
                    "description": "Enables this network to be secured by the validator set of another network. As to be seen on Neutron."
                },
                {
                    "const": "whitelisted-liquid",
                    "description": "Utilizes a protocol-permissioned whitelist to issue liquid staking derivatives. As seen on Crescent Network."
                },
                {
                    "const": "iqlusion-liquid",
                    "description": "Enables this network to permissionlessly issue validator-specific liquid staking derivatives without unbonding. Coming soon to Cosmos Hub."
                }
            ]
        },
        "logo_URIs": {
            "type": "object",
            "properties": {
                "png": {
                    "type": "string",
                    "format": "uri-reference"
                },
                "svg": {
                    "type": "string",
                    "format": "uri-reference"
                }
            }
        }
    }
}

=== 0semter0/cosmos-chain-registry/testnets/medastestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chain_name": "medasdigital-test",
  "status": "live",
  "network_type": "testnet",
  "pretty_name": "MedasDigital-Testnet",
  "chain_id": "medasdigital-test",
  "bech32_prefix": "medas",
  "daemon_name": "medasdigitald",
  "node_home": "$HOME/.medasdigital",
  "genesis": {
    "genesis_url": "https://github.com/oxygene76/medasdigital/tree/main/networks/testnet/genesis.json"
  },
  "key_algos": [
    "secp256k1"
  ],
  "slip44": 909,
  "fees": {
    "fee_tokens": [
      {
        "denom": "umedas",
        "fixed_min_gas_price": 0
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/oxygene76/medasdigital/",
    "recommended_version": "v0.1.0",
    "compatible_versions": [
      "v0.1.0"
    ]
  },
  "peers": {
    "persistent_peers": [
      {
        "id": "285378860d713ea3d544fddada9f4fe4e2bfd661",
        "address": "212.6.182.248:26656",
        "provider": "medas"
      },
      {
        "id": "16e82117d8ba811d84ab3e46e61cc809e108631e",
        "address": "212.6.182.248:26856",
        "provider": "medas"
      },
      {
        "id": "962d5a638d4dbc7accf3864bc49cfb16e2cfede8",
        "address": "212.6.182.242:26756",
        "provider": "medas"
      },
      {
        "id": "c77539667db234823d034e65a14f4f98a8fac082",
        "address": "64.251.18.192:26656",
        "provider": "medas"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.testnet.medas-digital.io:26657/",
        "provider": "medas"
      }
    ],
    "grpc": [
      {
        "address": "grpc.testnet.medas-digital.io:9090",
        "provider": "medas"
      }
    ],
    "rest": [
      {
        "address": "https://rest.testnet.medas-digital.io:1317/",
        "provider": "medas"
      }
    ]
  },
  "explorers": [
    {
      "kind": "bigdipper",
      "url": "http://explorer.testnet.medas-digital.io/",
      "tx_page": "http://explorer.testnet.medas-digital.io/transactions/${txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/microtick/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "microtick",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Microtick",
    "chain_id": "microtick-1",
    "bech32_prefix": "micro",
    "daemon_name": "mtm",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/microtick/stargate-genesis/master/genesis.json"
    },
    "codebase": {
        "git_repo": "https://github.com/microtick/mtzone",
        "recommended_version": "mtm-v2.0.5",
        "compatible_versions": [
            "mtm-v2.0.5"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "922043cd83af759dd5a0605b32991667e8fd4977",
                "address": "45.79.207.112:26656",
                "provider": "Microtick"
            },
            {
                "id": "885cc6b8bcc36d9fd0489f4bfa2d845c9b60f354",
                "address": "5.189.132.164:26656",
                "provider": "Spanish Node"
            },
            {
                "id": "9dc9863a6091f251de72d92d88141ddcf93a6ac2",
                "address": "46.226.128.217:26656",
                "provider": "3Tekos"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://api.microtick.zone/",
                "provider": "Microtick"
            },
            {
                "address": "http://95.217.109.223:26657",
                "provider": "Microtick"
            },
            {
                "address": "http://104.237.158.143:26657",
                "provider": "Microtick"
            }
        ]
    },
    "explorers": [
        {
            "kind": "ping-pub",
            "url": "https://ping.pub/microtick",
            "tx_page": "https://ping.pub/microtick/tx/${txHash}"
    },
        {
            "kind": "bigdipper",
            "url": "https://explorer.microtick.zone/",
            "tx_page": "https://explorer.microtick.zone/transactions/${txHash}"
        }
    ]
}

=== 0semter0/cosmos-chain-registry/cerberus/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "cerberus",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Cerberus",
    "chain_id": "cerberus-1",
    "bech32_prefix": "cerberus",
    "daemon_name": "cerberusd",
    "node_home": "$HOME/.cerberus",
    "genesis": {
        "genesis_url": "https://github.com/cerberus-zone/cerberus_genesis/blob/main/genesis.json"
    },
    "codebase": {
        "git_repo": "https://github.com/cerberus-zone/cerberus",
        "recommended_version": "v1.0.1",
        "compatible_versions": [
            "v1.0.1"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "d8a04beba9fb95c70368b303f701c36b4e3b4a63",
                "address": "185.215.165.29:26656"
            }
        ],
        "persistent_peers": [
            {
                "id": "4c3abff6e4a3e93b84babfc95df854861f83ac82",
                "address": "cerberus-seed.blockpane.com:26656",
                "provider": "blockpane"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc.cerberus.zone:26657/",
                "provider": "Cerberus"
            }
        ],
        "rest": [
            {
                "address": "https://api.cerberus.zone:1317/",
                "provider": "Cerberus"
            }
        ]
    },
    "explorers": [
        {
            "kind": "ping.pub",
            "url": "https://skynetexplorers.com/Cerberus",
            "tx_page": "https://skynetexplorers.com/Cerberus/tx/${txHash}"
        }
    ]
}

=== 0semter0/cosmos-chain-registry/secret/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "secret",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Secret Network",
    "chain_id": "secret-4",
    "bech32_prefix": "secret",
    "daemon_name": "secretd",
    "node_home": "$HOME/.secretd",
    "apis": {
        "rest": [
            {
                "address": "https://api.secretapi.io",
                "provider": "chainofsecrets"
            }
        ]
    }
}

=== 0semter0/cosmos-chain-registry/rebus/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "rebus",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Rebus",
    "chain_id": "reb_1111-1",
    "bech32_prefix": "rebus",
    "daemon_name": "rebusd",
    "node_home": "$HOME/.rebusd",
    "genesis": {
        "genesis_url": "https://github.com/rebuschain/rebus.mainnet/raw/master/reb_1111-1/genesis.zip"
    },
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "arebus"
            }
        ]
    },
    "staking": {
        "staking_tokens": [
            {
                "denom": "arebus"
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/rebuschain/rebus.core",
        "recommended_version": "v0.1.0",
        "compatible_versions": [
            "v0.1.0"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "9be95ccf0086b96b707115b7707ea73420b11b6b",
                "address": "159.223.152.53:26656"
            },
            {
                "id": "3a3e7123b9ae814b8d8517b6635d21b9ae45bf25",
                "address": "195.3.222.148:26656"
            },
            {
                "id": "d28516746773bfaeca4efa5537c0bf5990b8828e",
                "address": "65.21.229.33:27656"
            },
            {
                "id": "7197d316935ca7b7ac36da7d4a3a6df16cd286a7",
                "address": "93.170.72.118:26656"
            },
            {
                "id": "87102b5dd22c1d17f97197c078f23726ae3c6214",
                "address": "garagenodes.com:26656"
            },
            {
                "id": "b9b70240be5b970a4939ddd5cc9a45ff4be6c292",
                "address": "198.244.167.164:26656"
            },
            {
                "id": "9289288c444b781a18f13c69da42b99424442cbb",
                "address": "65.108.44.149:21656"
            },
            {
                "id": "f467e286567f94c89d39a5bcea0e1d68951299f9",
                "address": "146.59.81.204:34456"
            },
            {
                "id": "4ef77b2a17e71d2535b3c8ec11830708fc299705",
                "address": "209.222.98.90:26656"
            },
            {
                "id": "c301abd7abe536d7791eb139599a68ecaab4ffbc",
                "address": "65.108.6.121:26656"
            },
            {
                "id": "dda7abe32cc84a722cf6b1d2ee3b61ebe7ad71df",
                "address": "135.181.212.183:21656"
            },
            {
                "id": "07b84cf4b47a2e5ad251267716fe05bcf30330cd",
                "address": "65.21.170.3:29656"
            },
            {
                "id": "b4941d0929595b9f83d190559e1d7126fec91cb0",
                "address": "172.96.161.94:26656"
            },
            {
                "id": "ce8b36056ace01414fa7a92e43eaa5bfd8705dd4",
                "address": "138.201.141.76:26656"
            },
            {
                "id": "89ded0a3987d22e46b756fead439e2a4d25f23cb",
                "address": "185.144.99.30:26656"
            },
            {
                "id": "62859ddc0485dbb37b7442135b8d468c4b2222b3",
                "address": "65.108.132.239:36656"
            },
            {
                "id": "eeca453e3a1cf670c78e2255b8f0bd5a9443c30b",
                "address": "65.108.225.71:26656"
            },
            {
                "id": "a7dd6ba407b4567372073f0c675dc0fa9703929e",
                "address": "141.95.124.152:20106"
            },
            {
                "id": "170397e75ca2b0f4e9f3b1bb5d0d23f9b10f01c7",
                "address": "rebus-sentry-1.p2p.brocha.in:30544"
            },
            {
                "id": "c0b33353fb70d8d71dcb9c8848b3b4207bd56951",
                "address": "rebus-sentry-2.p2p.brocha.in:30547"
            },
            {
                "id": "e9fa8c32e4504013c37d04671a8882c9bfbc47a9",
                "address": "38.242.139.248:26656"
            },
            {
                "id": "fe11ed3335cbf0690d7f8f5cd6bcee025991e48e",
                "address": "213.239.218.199:26621"
            },
            {
                "id": "c88a9a3d3a41a164f8c1537514665e77ea0b54ac",
                "address": "[2a01:4f9:6b:2e5b::9]:26656"
            },
            {
                "id": "b8c42fcb311b47cdb8285b5697f661fbba5bf1a5",
                "address": "51.68.157.129:26656"
            },
            {
                "id": "e1ab57dc8fb74bc238351e063da4de1e4ed78696",
                "address": "142.44.143.93:26656"
            },
            {
                "id": "5882961bd31831bf912c0d5fe5486da100c75d6b",
                "address": "65.109.54.110:36656"
            },
            {
                "id": "011a80b75d4986be1c71267785341e172d4aa321",
                "address": "198.244.228.17:43656"
            },
            {
                "id": "f5ceadfe92dc08bb57a30977409c8b195b822dc7",
                "address": "194.34.232.124:26656"
            },
            {
                "id": "c876aaf9c3626272666bdd161155166e7534c2a0",
                "address": "65.108.206.56:31656"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rebus.rpc.manticore.team:443/",
                "provider": "MantiCore"
            },
            {
                "address": "https://rpc.rebus.nodestake.top/",
                "provider": "NodeStake"
            }
        ],
        "rest": [
            {
                "address": "https://rebus.api.manticore.team:443/",
                "provider": "MantiCore"
            },
            {
                "address": "https://api.rebus.nodestake.top/",
                "provider": "NodeStake"
            }
        ],
        "grpc": [
            {
                "address": "https://rebus.grpc.manticore.team:443/",
                "provider": "MantiCore"
            },
            {
                "address": "https://grpc.rebus.nodestake.top/",
                "provider": "NodeStake"
            }
        ]
    },
    "explorers": [
        {
          "kind": "ping.pub",
          "url": "https://explorer.nodestake.top/rebus",
          "tx_page": "https://explorer.nodestake.top/rebus/txs/${txHash}"
        },
        {
          "kind": "ping.pub",
          "url": "https://mainnet.manticore.team/rebus",
          "tx_page": "https://mainnet.manticore.team/rebus/tx/${txHash}"
        }
      ]
}

=== 0semter0/cosmos-chain-registry/testnets/saagetestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chain_name": "saagetestnet",
  "status": "live",
  "network_type": "testnet",
  "pretty_name": "Saage-Testnet-5",
  "chain_id": "sit-5",
  "bech32_prefix": "sge",
  "daemon_name": "saaged",
  "node_home": "$HOME/.saage",
  "genesis": {
    "genesis_url": "https://github.com/saage-tech/network-testnet-1/blob/master/networks/saage-testnet-5/genesis.json"
  },
  "key_algos": ["secp256k1"],
  "slip44": 909,
  "fees": {
    "fee_tokens": [
      {
        "denom": "usge",
        "fixed_min_gas_price": 0
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/saage-tech/saage-testnet-1",
    "recommended_version": "v0.6.0",
    "compatible_versions":["v0.6.0"]
  },
  "peers": {
    "persistent_peers": [
      {
        "id": "c1e005ef1d63a3e543d2542dffaabdd65a381bb3",
        "address": "3.82.54.192:26656",
        "provider": "devopsNexus"
      },
      {
        "id": "8313705fa5c5b1e4a8c45e99df8ed216604b9310",
        "address": "3.235.109.126:26656",
        "provider": "darkRealm"
      },
      {
        "id": "0a43064d5706673220a8a49f6fe144b8a1c53f7c",
        "address": "44.201.51.199:26656",
        "provider": "scorpionKing"
      },
      {
        "id": "80ccda3f9a1fb765036fa1b97b504a697189ec4f",
        "address": "3.235.167.226:26656",
        "provider": "nitka"
      },
      {
        "id": "8f5670953c3af833746d4d62fdda380e6500480d",
        "address": "54.187.111.220:26656",
        "provider": "nitka"
      },
      {
        "id": "f8d5f23f741ccbe7da0f7112e3e55bf0fde1e7b5",
        "address": "54.226.144.104:26656",
        "provider": "validictator"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://sentry.testnet.saage.io:26657/",
        "provider": "saage"
      }
    ],
    "grpc": [
      {
        "address": "sentry.testnet.saage.io:9090",
        "provider": "saage"
      }
    ],
    "rest": [
      {
          "address": "https://sentry.testnet.saage.io:1317/",
          "provider": "saage"
      }
    ]
  },
  "explorers": [
    {
      "kind": "bigdipper",
      "url": "https://blockexplorer-1.testnet.saage.io/",
      "tx_page": "https://blockexplorer-1.testnet.saage.io/transactions/{txHash}"
    }
  ]
}

=== 0semter0/cosmos-chain-registry/testnets/permtestnet/chain.json
{
    "$schema": "../../chain.schema.json",
    "chain_name": "permtestnet",
    "status": "live",
    "network_type": "testnet",
    "pretty_name": "Perm Testnet",
    "chain_id": "testnet-1",
    "bech32_prefix": "perm",
    "daemon_name": "permd",
    "node_home": "$HOME/.perm",
    "key_algos": [
      "secp256k1"
    ],
    "slip44": 118,
    "fees": {
      "fee_tokens": [
        {
          "denom": "uperm",
          "low_gas_price": 0.0025,
          "average_gas_price": 0.0025,
          "high_gas_price": 0.0024
        }
      ]
    },
    "staking": {
      "staking_tokens": [
        {
          "denom": "uperm"
        }
      ]
    },
    "codebase": {
      "git_repo": "https://github.com/Loop-Protocol/perm.git",
      "recommended_version": "v1.0.0",
      "compatible_versions": [
        "v1.0.0"
      ],
      "cosmos_sdk_version": "0.45",
      "consensus": {
        "type": "tendermint",
        "version": "0.34"
      },
      "cosmwasm_version": "0.30",
      "cosmwasm_enabled": true,
      "ibc_go_version": "4.3.0",
      "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/Loop-Protocol/testnet/main/genesis.json"
      },
      "versions": [
        {
          "name": "v1.0.0",
          "recommended_version": "v1.0.0",
          "compatible_versions": [
            "v1.0.0"
          ],
          "cosmos_sdk_version": "0.45",
          "consensus": {
            "type": "tendermint",
            "version": "0.34"
          },
          "cosmwasm_version": "0.30",
          "cosmwasm_enabled": true,
          "ibc_go_version": "4.3.0"
        },
        {
          "name": "v1.0.0",
          "recommended_version": "v1.0.0",
          "compatible_versions": [
            "v1.0.0"
          ],
          "cosmos_sdk_version": "0.45",
          "consensus": {
            "type": "tendermint",
            "version": "0.34"
          },
          "cosmwasm_version": "0.30",
          "cosmwasm_enabled": true,
          "ibc_go_version": "4.3.0"
        }
      ]
    },
    "peers": {
      "seeds": [],
      "persistent_peers": []
    },
    "apis": {
      "rpc": [
        {
          "address": "http://perm-1-1412376094.ap-south-1.elb.amazonaws.com",
          "provider": "Perm Network"
        }
      ],
      "rest": [
        {
          "address": "http://pem-2-343400911.ap-south-1.elb.amazonaws.com/",
          "provider": "Perm Network"
        }
      ],
      "grpc": [
        {
          "address": "http://perm-3-913721738.ap-south-1.elb.amazonaws.com/",
          "provider": "Perm Network"
        }
      ]
    },
    "explorers": [
      {
        "kind": "bigdipper",
        "url": "https://explorer.testnet.perm.ooo/",
        "tx_page": "https://explorer.testnet.perm.ooo/transactions/${txHash}"
      }
    ]
  }

=== 0semter0/cosmos-chain-registry/quicksilver/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "quicksilver",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Quicksilver",
  "chain_id": "quicksilver-1",
  "daemon_name": "quicksilverd",
  "node_home": "$HOME/.quicksilver",
  "bech32_prefix": "quick",
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "uqck",
        "fixed_min_gas_price": 0.0001
      }
    ]
  },
  "staking": {
    "staking_tokens": [
      {
        "denom": "uqck"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/ingenuity-build/quicksilver",
    "recommended_version": "v1.0.0",
    "compatible_versions": [
      "v1.0.0"
    ],
    "genesis": {
      "genesis_url": "https://github.com/ingenuity-build/mainnet/raw/main/genesis.json"
    }
  },
  "peers": {
    "seeds": [],
    "persistent_peers": []
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.quicksilver.zone:443",
        "provider": "Quicksilver"
      },
      {
        "address": "https://rpc-quicksilver-ia.cosmosia.notional.ventures:443",
        "provider": "Notional"
      }
    ],
    "rest": [
      {
        "address": "http://lcd.quicksilver.zone:443/",
        "provider": "Quicksilver"
      },
      {
        "address": "https://api-quicksilver-ia.cosmosia.notional.ventures:443",
        "provider": "Notional"
      }
    ],
    "grpc": [
      {
        "address": "grpc-quicksilver-ia.cosmosia.notional.ventures:443",
        "provider": "Notional"
      }
    ]
  },
  "explorers": [
    {
      "kind": "mintscan",
      "url": "https://www.mintscan.io/quicksilver",
      "tx_page": "https://www.mintscan.io/quicksilver/txs/${txHash}",
      "account_page": "https://www.mintscan.io/quicksilver/account/${accountAddress}"
    }
  ]
}
